import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          style={{
            position: "absolute",
            zIndex: -1,
            width: "100%",
            height: "100%",
          }}
        >
          <Image
            alt="space"
            src="/space.jpg"
            quality={100}
            fill
            sizes="100vw"
            style={{ objectFit: "cover" }}
          />
        </div>
        <Navbar />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
